
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NProgressBar from "./nprogress";

const poppins = Poppins({
  weight: ['400', '700'],
  variable: "--font-poppins",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`${poppins.variable} antialiased`} cz-shortcut-listen="true">
        <NProgressBar />
        {children}
      </body>
    </html>
  );
}
